"""
Django settings for agrofarm project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_&jfbho#!l+pq-rgg2a=i1(6c$8us!$z4ju8tz+4(==44&f6d&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'Localhost',
]


# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'debug_toolbar',
    'baton.autodiscover',
    'crispy_forms',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'agrofarm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.cart'
            ],
        },
    },
]

WSGI_APPLICATION = 'agrofarm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'agrofarm',
            'USER': 'root',
            'PASSWORD': 'Soy@ib55',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

INTERNAL_IPS = [
    '127.0.0.1',
]

AUTH_USER_MODEL = 'core.CustomUser'


# Gmail Mail Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mdsoyaib2025@gmail.com'
EMAIL_HOST_PASSWORD = 'tustqqaczjtbmeyl'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'noreply@shop.com'


BATON = {
    'SITE_HEADER': '<img src=/static/core/img/agrofarm.png width="100%">',
    'SITE_TITLE': 'Green Agro',
    'INDEX_TITLE': 'AgroFarm Admin Dashboard',
    'SUPPORT_HREF': '#',
    'COPYRIGHT': 'copyright © 2021 <a href="#">Green Agro</a>', # noqa
    'POWERED_BY': '<a href="#">Md Soyaib</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_FORM': True,
    'COLLAPSABLE_USER_AREA': False,
    'MENU_ALWAYS_COLLAPSED': False,
    'MENU_TITLE': 'Menu',
    'GRAVATAR_DEFAULT_IMG': 'https://s.gravatar.com/avatar/dca575606d7f51251c2be9fc83ba9fc1?s=60',
    'LOGIN_SPLASH': '/static/core/img/login-splash.png',
    'MENU': (
        {'type': 'free', 'label': ' Dashboard', 'icon': 'fa fa-home', 'url': 'http://127.0.0.1:8000/admin/'},

        {'type': 'app', 'name': 'auth', 'label': 'Authentication', 'icon': 'fa fa-lock',
         'models': (
             {'name': 'group', 'label': 'Groups'},
            )
        },

        {'type': 'title', 'label': 'Inventory Management', 'apps': ('auth', )},

        {'type': 'free', 'label': 'Inhouse Management', 'icon': 'fa fa-leaf', 'default_open': False, 'children': [
            {'type': 'free', 'label': ' View Inhouse Products', 'url': 'http://127.0.0.1:8000/admin/core/inhouseproduct/'},
            {'type': 'free', 'label': ' Add New Inhouse Product', 'url': 'http://127.0.0.1:8000/admin/core/inhouseproduct/add/'},
            {'type': 'free', 'label': ' View Inhouse Stocks', 'url': 'http://127.0.0.1:8000/admin/core/inhousestock/'},
            {'type': 'free', 'label': ' Add New Inhouse Stock', 'url': 'http://127.0.0.1:8000/admin/core/inhousestock/add/'},
        ]},

        {'type': 'free', 'label': 'Manage Instruments', 'icon': 'fa fa-tools', 'default_open': False, 'children': [
            {'type': 'free', 'label': ' View Instruments', 'url': 'http://127.0.0.1:8000/admin/core/instrument/'},
            {'type': 'free', 'label': ' Add New Instrument', 'url': 'http://127.0.0.1:8000/admin/core/instrument/add/'},
        ]},

        {'type': 'free', 'label': 'Manage Workers', 'icon': 'fa fa-users', 'default_open': False, 'children': [
            {'type': 'free', 'label': ' View Workers', 'url': 'http://127.0.0.1:8000/admin/core/worker/'},
            {'type': 'free', 'label': ' Add New Worker', 'url': 'http://127.0.0.1:8000/admin/core/worker/add/'},
        ]},

        {'type': 'free', 'label': 'Manage Farm Expenses', 'icon': 'fa fa-dollar-sign', 'default_open': False, 'children': [
            {'type': 'free', 'label': ' View Expenses', 'url': 'http://127.0.0.1:8000/admin/core/expenses/'},
            {'type': 'free', 'label': ' Add New Expense', 'url': 'http://127.0.0.1:8000/admin/core/expenses/add/'},
        ]},

        {'type': 'free', 'label': 'Manage Products', 'icon': 'fab fa-product-hunt', 'default_open': False, 'children': [
            {'type': 'free', 'label': ' View Products', 'url': 'http://127.0.0.1:8000/admin/core/product/',},
            {'type': 'free', 'label': ' Add New Product', 'url': 'http://127.0.0.1:8000/admin/core/product/add/'},
        ]},

        {'type': 'free', 'label': 'Manage Product Stock', 'icon': 'fas fa-cubes', 'default_open': False, 'children': [
             {'type': 'free', 'label': ' View Product Stocks', 'url': 'http://127.0.0.1:8000/admin/core/productstock/'},
             {'type': 'free', 'label': ' Add New Product Stock', 'url': 'http://127.0.0.1:8000/admin/core/productstock/add/',},
        ]},

        {'type': 'free', 'label': 'Manage Orders', 'icon': 'fas fa-shopping-cart', 'default_open': False, 'children': [
            {'type': 'free', 'label': ' View Orders', 'url': 'http://127.0.0.1:8000/admin/core/order/'},
            {'type': 'free', 'label': ' View Order Details', 'url': 'http://127.0.0.1:8000/admin/core/orderdetail/'},
            {'type': 'free', 'label': ' Order Report', 'url': '/order_report/'},
        ]},

        {'type': 'title', 'label': 'Custom Management', 'icon': 'fas fa-cogs', 'apps': ('auth', )},
        {'type': 'free', 'label': ' Users', 'icon': 'fas fa-user', 'url': 'http://127.0.0.1:8000/admin/core/customuser/'},
        {'type': 'free', 'label': ' Update Website Info', 'icon': 'fas fa-globe', 'url': 'http://127.0.0.1:8000/admin/core/websiteinfo/'},
    ),
}


LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
CRISPY_TEMPLATE_PACK = "bootstrap4"

CART_SESSION_ID = 'cart'
