# Generated by Django 3.1.7 on 2021-05-03 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default=None, max_length=255, null=True)),
                ('last_name', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('session_token', models.CharField(default=0, max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.FileField(upload_to='core/user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('ELECTRICITY BILL', 'Electricity Bill'), ('LAND BILL', 'Land Bill'), ('WORKER SALARY', 'Worker Salary'), ('INSTRUMENT', 'Instrument'), ('SEED', 'Seed'), ('FERTILIZER', 'Fertilizer'), ('OTHERS', 'Others')], max_length=50)),
                ('exp_name', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('NON-PAID', 'Non-Paid')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='InhouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Fertilizer', 'FERTILIZER'), ('Seed', 'SEED')], max_length=50)),
                ('unit_type', models.CharField(choices=[('KILOGRAM', 'Kilogram'), ('LITER', 'Liter'), ('PIECE', 'Piece'), ('CUSTOM', 'Custom')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CANCELED', 'Canceled'), ('DELIVERED', 'Delivered')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.PositiveIntegerField()),
                ('unit_type', models.CharField(choices=[('KILOGRAM', 'Kilogram'), ('LITER', 'Liter'), ('PIECE', 'Piece'), ('CUSTOM', 'Custom')], max_length=20)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('LIQUID', 'Liquid'), ('DAIRY', 'Dairy'), ('GROCERY', 'Grocery')], max_length=50)),
                ('product_image', models.ImageField(blank=True, default='/core/images/default.png', null=True, upload_to='core/images')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('open_time', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('map_city', models.CharField(max_length=255)),
                ('map_phone', models.CharField(max_length=255)),
                ('map_address', models.CharField(max_length=255)),
                ('about_us', models.TextField()),
                ('contact_info', models.TextField()),
                ('payment_method', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name (required)', max_length=100)),
                ('phone_number1', models.CharField(max_length=14, unique=True)),
                ('phone_number2', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('CUSTOM', 'Custom')], help_text='Select gender', max_length=20)),
                ('task', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in', models.PositiveIntegerField()),
                ('stock_out', models.PositiveIntegerField(blank=True, null=True)),
                ('current_stock', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='InhouseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in', models.PositiveIntegerField()),
                ('stock_out', models.PositiveIntegerField(blank=True, null=True)),
                ('current_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date time created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date time updated at')),
                ('inhouse_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.inhouseproduct')),
            ],
        ),
    ]
