# Generated by Django 3.1.7 on 2021-05-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210521_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
