# Generated by Django 3.1.7 on 2021-05-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='user',
        ),
    ]
