# Generated by Django 3.1.7 on 2021-05-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210525_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(auto_created=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
