# Generated by Django 3.1.7 on 2021-05-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
