# Generated by Django 3.1.7 on 2021-05-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210527_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Kilogram', 'Kilogram'), ('Liter', 'Liter'), ('Dozen', 'Dozen'), ('Piece', 'Piece'), ('Custom', 'Custom')], max_length=20),
        ),
    ]
