# Generated by Django 3.1.7 on 2021-06-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210623_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='email',
        ),
    ]
