# Generated by Django 3.1.7 on 2021-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_billinginfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
